contracts = [
"account",
"alloc",
"atomic_swap",
"atomic_multiswap",
"auth",
"cross_contract/contract_a",
"cross_contract/contract_b",
"custom_types",
"deep_contract_auth",
"deployer/contract",
"deployer/deployer",
"errors",
"eth_abi",
"events",
"fuzzing",
"increment",
"liquidity_pool",
"logging",
"mint-lock",
"simple_account",
"single_offer",
"timelock",
"token",
"upgradeable_contract/old_contract",
"upgradeable_contract/new_contract",
"workspace",
]
